---

- name: Install i3 windowmanager and components
  community.general.pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - i3lock
      - i3status-rust
      - dmenu
      - feh
      - dunst
      - rofi
      - picom
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Copy Xorg mouse configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
  with_items:
    - 00-keyboard.conf
    - 50-mouse-acceleration.conf
    - 50-mouse-deceleration.conf
