---

- name: install dunst server
  ansible.builtin.import_tasks: dunst.yml

- name: install system fonts
  ansible.builtin.import_tasks: fonts.yml

- name: install i3 window manager
  ansible.builtin.import_tasks: i3.yml
